### ISSUE TITLE
Exception Handling

### ISSUE THREAD

**Issue by imerljak** [imerljak/aceleradev-mapfood#13]
Essa API tem algumas validações e regras a serem seguidas na estrutura da requisição, etc.
Dessa forma, precisamos de um mecanismo que facilite o feedback da API para o cliente sobre os erros e o que ta acontecendo.

No momento o que acontece é que, se tiver algo incorreto é lançado uma exceção ou retorna uma resposta padrão do `javax.validation` (Aquelas annotation @NotNull etc nos modelos).

Precisamos de algo um pouco mais amigavel e de preferencia com uma estrutura padronizada p/ retornar como resposta em caso de erro.

O Spring possui uma funcionalidade que permite registrar **handlers** para exceções lançadas na aplicação, o que possibilita desacoplar nosso código de negócio do de validação. Sugiro que a gente utilize essa funcionalidade pra nosso benefício.

Dêem uma olhada nesse tutorial: [Error Handling for REST with Spring Boot](https://www.baeldung.com/exception-handling-for-rest-with-spring)

As exceções da api (até o momento) estão em `mapfood.exceptions`.

**Comment by imerljak** [comment]
@DiovaneMendes @sarah-onix @hoytei 

Aqui também.. quem quiser se habilitar. (isso é bem legal pra 'usabilidade' da api. então seria bem importante)

**Comment by DiovaneMendes** [comment]
Branch 'tratamento-excecoes' concluida
