### ISSUE TITLE
CodeStyle

### ISSUE THREAD

**Issue by imerljak** [imerljak/aceleradev-mapfood#9]
Precisamos definir algumas regras de estilo p/ evitar ficar comitando espaço em branco (diferença de tabulação, espaços x tabs, etc..)

Aceitando sugestões. (que não seja usar tabs :nauseated_face: )

@hoytei , @DiovaneMendes , @sarah-onix

**Comment by DiovaneMendes** [comment]
Podemos usar um espaço só.
